/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CurveProxyLogicInterface extends ethers.utils.Interface {
  functions: {
    "add_liquidity(address,bytes4,uint256,uint256,address)": FunctionFragment;
    "remove_liquidity_one_coin(address,address,int128)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "add_liquidity",
    values: [string, BytesLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity_one_coin",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "add_liquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity_one_coin",
    data: BytesLike
  ): Result;

  events: {};
}

export class CurveProxyLogic extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CurveProxyLogicInterface;

  functions: {
    add_liquidity(
      curve: string,
      curveFunctionSig: BytesLike,
      curvePoolSize: BigNumberish,
      curveUnderlyingIndex: BigNumberish,
      underlying: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "add_liquidity(address,bytes4,uint256,uint256,address)"(
      curve: string,
      curveFunctionSig: BytesLike,
      curvePoolSize: BigNumberish,
      curveUnderlyingIndex: BigNumberish,
      underlying: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    remove_liquidity_one_coin(
      curve: string,
      curveLp: string,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "remove_liquidity_one_coin(address,address,int128)"(
      curve: string,
      curveLp: string,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  add_liquidity(
    curve: string,
    curveFunctionSig: BytesLike,
    curvePoolSize: BigNumberish,
    curveUnderlyingIndex: BigNumberish,
    underlying: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "add_liquidity(address,bytes4,uint256,uint256,address)"(
    curve: string,
    curveFunctionSig: BytesLike,
    curvePoolSize: BigNumberish,
    curveUnderlyingIndex: BigNumberish,
    underlying: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  remove_liquidity_one_coin(
    curve: string,
    curveLp: string,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "remove_liquidity_one_coin(address,address,int128)"(
    curve: string,
    curveLp: string,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    add_liquidity(
      curve: string,
      curveFunctionSig: BytesLike,
      curvePoolSize: BigNumberish,
      curveUnderlyingIndex: BigNumberish,
      underlying: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "add_liquidity(address,bytes4,uint256,uint256,address)"(
      curve: string,
      curveFunctionSig: BytesLike,
      curvePoolSize: BigNumberish,
      curveUnderlyingIndex: BigNumberish,
      underlying: string,
      overrides?: CallOverrides
    ): Promise<void>;

    remove_liquidity_one_coin(
      curve: string,
      curveLp: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "remove_liquidity_one_coin(address,address,int128)"(
      curve: string,
      curveLp: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    add_liquidity(
      curve: string,
      curveFunctionSig: BytesLike,
      curvePoolSize: BigNumberish,
      curveUnderlyingIndex: BigNumberish,
      underlying: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "add_liquidity(address,bytes4,uint256,uint256,address)"(
      curve: string,
      curveFunctionSig: BytesLike,
      curvePoolSize: BigNumberish,
      curveUnderlyingIndex: BigNumberish,
      underlying: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    remove_liquidity_one_coin(
      curve: string,
      curveLp: string,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "remove_liquidity_one_coin(address,address,int128)"(
      curve: string,
      curveLp: string,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    add_liquidity(
      curve: string,
      curveFunctionSig: BytesLike,
      curvePoolSize: BigNumberish,
      curveUnderlyingIndex: BigNumberish,
      underlying: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "add_liquidity(address,bytes4,uint256,uint256,address)"(
      curve: string,
      curveFunctionSig: BytesLike,
      curvePoolSize: BigNumberish,
      curveUnderlyingIndex: BigNumberish,
      underlying: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    remove_liquidity_one_coin(
      curve: string,
      curveLp: string,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "remove_liquidity_one_coin(address,address,int128)"(
      curve: string,
      curveLp: string,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
